all:
  vars:
    ansible_user: mocops
  children:
    control_hosts:
      hosts:
        control.massopen.virt:
    mail_servers:
      hosts:
        mail.massopen.virt:
    auth_servers:
      hosts:
        sso1.massopen.virt:
        sso2.massopen.virt:
    hil_servers:
      hosts:
        kumo-hil-client.infra.massopen.virt:
